sudo: required
services:
  - docker

before_install:
  - docker build -t arthurrfanti/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arthurrfanti/react-test npm test

after_success:
  - docker build -t arthurrfanti/multi-client ./client
  - docker build -t arthurrfanti/multi-nginx ./nginx
  - docker build -t arthurrfanti/multi-server ./server
  - docker build -t arthurrfanti/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push arthurrfanti/multi-client
  - docker push arthurrfanti/multi-nginx
  - docker push arthurrfanti/multi-server
  - docker push arthurrfanti/multi-worker

deploy:
  provider: elasticbeanstalk
  edge: true
  region: sa-east-1
  app: multi-docker
  env: MulitDocker-env
  bucket_name: elasticbeanstalk-sa-east-1-102935538682
  bucket_path: docker-multi
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
